feat: Deal switching
fluencelabs/deal pull request #176
Opened 2023-12-22 20:48 UTC by elshan-eth

2024-01-04 22:18 UTC, AlcibiadesCleinias requested changes

2024-01-04 22:18 UTC, AlcibiadesCleinias commented on src/core/modules/market/Matcher.sol
> +                if (computeUnit.deal != address(0) || peer.commitmentId == bytes32(0x000000000)) {
le problema

2024-01-11 12:20 UTC, elshan-eth commented on src/core/modules/capacity/Capacity.sol
> +    function _commitCommitmentSnapshot(
This should be described in a notion because snapshots are a big topic. Let me leave TODO to do this in the future.

2024-01-11 12:22 UTC, elshan-eth commented on src/core/modules/capacity/interfaces/ICapacity.sol
> +        uint256 nextAdditionalActiveUnitCount;
It's internal structure. Let's focus on describing the public API and describe the internal later

2024-01-11 12:23 UTC, elshan-eth commented on src/core/modules/capacity/Capacity.sol
> +        _setActiveUnitCount(activeUnitCount() - 1);
activeUnitCount() - global quantity in all CC
cc.info.activeUnitCount - activeUnitCount in CC

2024-01-11 12:26 UTC, elshan-eth commented on src/core/modules/capacity/Capacity.sol
> +    function createCommitment(bytes32 peerId, uint256 duration, address delegator, uint256 rewardDelegationRate)
The contract is called a capacity. So that it can be omitted in events and functions. I think the event will need to change.

2024-01-11 12:28 UTC, AlcibiadesCleinias commented on script/Deploy.s.sol
> +        bool doNeedToRedeployMarket = _doNeedToRedeploy("MarketImpl", "Market");
I renamed in https://github.com/fluencelabs/deal/pull/184

2024-01-12 09:04 UTC, elshan-eth commented on README.md
> +make create-pure-market-local
`# Requirements

- foundry
- makefile (TODO)
- node version 18.16

# Contract

## Install Foundry

https://book.getfoundry.sh/`

2024-01-12 09:04 UTC, elshan-eth commented on README.md
> +make create-pure-market-local
We have it in Readme

2024-01-12 09:10 UTC, elshan-eth commented on src/core/modules/capacity/Capacity.sol
> +        unitProofsInfo.lastSuccessEpoch = epoch;
I changed `lastSuccessEpoch` to `lastMinProofsEpoch`.  lastMinProofsEpoch is the last epoch when a unit sends proof more than min proofs.

2024-01-12 13:07 UTC, merged