feat: New integration tests
fluencelabs/deal pull request #264
Opened 2024-02-16 10:47 UTC by akim-bow

2024-02-19 13:05 UTC, AlcibiadesCleinias requested changes

2024-02-19 13:05 UTC, AlcibiadesCleinias commented on integration-tests/src/deal-matcher.test.ts
> +      // expect(matchedOffersOut.offers.length).toBe(1); // At least with one previously created offer it matched.
ph, I forgot when we will unlock this part?

2024-02-19 13:05 UTC, AlcibiadesCleinias commented on integration-tests/src/offer.test.ts
> +const ip = await dns.lookup("akim-dev.dev.fluence.dev");
what this IP is about?

2024-02-29 18:56 UTC, akim-bow commented on integration-tests/src/offer.test.ts
> +const ip = await dns.lookup("akim-dev.dev.fluence.dev");
Removed, thanks

2024-02-29 18:57 UTC, akim-bow commented on integration-tests/src/deal-matcher.test.ts
> +      // expect(matchedOffersOut.offers.length).toBe(1); // At least with one previously created offer it matched.
Later, need to interatively enable tests one by one

2024-03-01 11:56 UTC, nahsi requested changes

2024-03-01 11:56 UTC, nahsi commented on .github/workflows/artifacts.yml
> +
```suggestion
```
It should go to test.yml

2024-03-01 11:56 UTC, nahsi commented on integration-tests/package.json
> +    "@fluencelabs/deal-ts-clients": "file:fluencelabs-deal-ts-clients-0.7.0.tgz",
```suggestion
    "@fluencelabs/deal-ts-clients": "file:../ts-client",
```
Or else we need to build this archive manually on every change

2024-03-01 11:56 UTC, nahsi commented on integration-tests/src/offer.test.ts
> +const ip = await dns.lookup("akim-dev.dev.fluence.dev");
Isn't it a temporary host that will go down any minute? :) Why it has to connect there?

2024-03-01 15:02 UTC, akim-bow commented on integration-tests/src/offer.test.ts
> +const ip = await dns.lookup("akim-dev.dev.fluence.dev");
Thanks! I forgot to push these changes which remove that.

2024-03-01 15:12 UTC, akim-bow commented on .github/workflows/artifacts.yml
> +
Thanks! Moved

2024-03-01 15:30 UTC, closed without merging